data_folder = "../dataset/"
output_folder = "../processed/"

# first 10% of the data will be used for validation
validate = true
validation_ratio = 0.1

# common noise types
[noise_types.pure]
[noise_types.noise]
[noise_types.missing]
[noise_types.duplicate]
[noise_types.delay]

# the following parameters are used to generate noise
[noise_types.noise.low]
feature_ratio = 0.2
intensity = 0.1

[noise_types.noise.high]
feature_ratio = 0.5
intensity = 0.3

[noise_types.missing.low]
feature_ratio = 0.1
missing_ratio = 0.05

[noise_types.missing.high]
feature_ratio = 0.2
missing_ratio = 0.1

[noise_types.duplicate.low]
feature_ratio = 0.2
duplicate_ratio = 0.03
duplicate_length = 10

[noise_types.duplicate.high]
feature_ratio = 0.3
duplicate_ratio = 0.08
duplicate_length = 30

[noise_types.delay.low]
feature_ratio = 0.2
delay_length = 10

[noise_types.delay.high]
feature_ratio = 0.3
delay_length = 20

[noise_types.mix_1]
types = ['noise', 'missing']

[noise_types.mix_2]
types = ['noise', 'duplicate']

[noise_types.mix_3]
types = ['noise', 'delay']

[noise_types.mix_4]
types = ['missing', 'duplicate']

[noise_types.mix_5]
types = ['missing', 'delay']

[noise_types.mix_6]
types = ['duplicate', 'delay']

[noise_types.mix_7]
types = ['noise', 'missing', 'duplicate']

[noise_types.mix_8]
types = ['noise', 'missing', 'delay']

[noise_types.mix_9]
types = ['noise', 'duplicate', 'delay']

[noise_types.mix_10]
types = ['missing', 'duplicate', 'delay']

[noise_types.mix_all]
types = ['noise', 'missing', 'duplicate', 'delay']
