data_folder = "../dataset/"
output_folder = "../processed_dataset/"

[low_quality_types.pure]

[[low_quality_types.noise]]
level = "low"
feature_ratio = 0.5
intensity = 0.3

[[low_quality_types.noise]]
level = "high"
feature_ratio = 0.8
intensity = 0.7

[[low_quality_types.missing]]
level = "low"
feature_ratio = 0.2
missing_ratio = 0.05

[[low_quality_types.missing]]
level = "high"
feature_ratio = 0.5
missing_ratio = 0.1

[[low_quality_types.duplicate]]
level = "low"
feature_ratio = 0.2
duplicate_ratio = 0.03
duplicate_length = 15

[[low_quality_types.duplicate]]
level = "high"
feature_ratio = 0.5
duplicate_ratio = 0.08
duplicate_length = 50

[[low_quality_types.delay]]
level = "low"
feature_ratio = 0.2
delay_length = 100

[[low_quality_types.delay]]
level = "high"
feature_ratio = 0.4
delay_length = 200

[[low_quality_types.mismacth]]
level = "low"
feature_ratio = 0.2
relative_frequency = 50

[[low_quality_types.mismacth]]
level = "high"
feature_ratio = 0.6
relative_frequency = 100